services:
 grafana:
    image: grafana/grafana


    ports:
      - 3000:3000
    volumes:
      #- grafana_data:/var/lib/grafana
      - /mnt/SSD240/data/grafana/data:/var/lib/grafana
      - /mnt/SSD240/data/grafana/dashboards:/var/lib/grafana/dashboards
      - /mnt/SSD240/data/grafana/provisioning:/etc/grafana/provisioning
      #- ./grafana/config/custom.ini:/etc/grafana/grafana.ini
      #- ./grafana/certs:/etc/ssl:ro
    restart: always
    networks:
       -  monitoring
    container_name: grafana

 prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - /mnt/SSD240/data/prometheus/_conf:/etc/prometheus/
     # - ./prometheus_conf:/etc/prometheus/
      - /mnt/SSD240/data/prometheus/_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=365d'
    ports:
      - 9090:9090
    restart: always
    networks: 
       - monitoring
    container_name: prometheus

 influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks: 
      - monitoring
    ports:
      - "8086:8086"
    volumes:
      - /mnt/SSD240/data/influxdb/data:/var/lib/influxdb
      - /mnt/SSD240/data/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /mnt/SSD240/data/influxdb/init:/docker-entrypoint-initdb.d

 cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - monitoring
    ports:
    - 9101:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

 nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring


networks:
    monitoring:
