version: '3'

services:
  db:
    image: linuxserver/mariadb:alpine
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: exampledb
      MARIADB_USER: mysql_user
      MARIADB_PASSWORD: userpwd
    volumes:
      - /mnt/SSD240/data/mariadb/config/databases:/config/databases
    ports:
      - "3306:3306"
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST="db"
      - PMA_ARBITRARY=1 
